### PR TITLE
issue/3187 General bugs and fixes

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes https://github.com/adaptlearning/adapt_framework/issues/3187
fixes https://github.com/adaptlearning/adapt_framework/issues/3166

### Changed
* Check completion rather than force it on article
* Use same infinity measure throughout
* Blocks have to be explicitly set to `_branching._isEnabled: false` to match the schema

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

**Comment by chrisgillison** [comment]
Without adapt-contrib-trickle involved this is working perfectly and is great. But if trickle is enabled on the block containing the mcq, the trickle div is added to the html, but when the mcq submit button is clicked,  the trickle button isn't appearing or getting activated.
FW 5.15.1
adapt-contrib-trickle 4.0.6 (+ these file changes)
adapt-contrib-mcq 4.1.0

**Comment by oliverfoster** [comment]
This is only meant to work with the latest trickle.

**Comment by chrisgillison** [comment]
Ahh - sorry I thought the master would be the one to use but now see that the json-schema branch is ahead. Now working perfectly, and just what I need! Many thanks @oliverfoster

**Pull request merged**
